global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'node_exporter'

  - job_name: 'backend'
    static_configs:
      - targets: ['api:3001']
        labels:
          instance: 'backend-api'